apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: be
  name: be
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 ()
      creationTimestamp: null
      labels:
        io.kompose.service: be
    spec:
      containers:
      - env:
        - name: DJANGO_SETTINGS_MODULE
          value: backend.docker_settings
        image: be
        name: be
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
