version: "3"

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "forums"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - mysqldb:/var/lib/mysql
    networks:
      backend:
        aliases:
          - database
  be:
    container_name: be
    build: backend
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DJANGO_SETTINGS_MODULE=backend.docker_settings
    networks:
      - backend
  fe:
    container_name: fe
    build: frontend
    ports:
      - "80:80"
    depends_on:
      - be
volumes:
  mysqldb:
networks:
  backend:
