"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 2.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

from backend.settings import *

DATABASES = {
    'default': {
        'NAME': 'forums',
        'ENGINE': 'mysql.connector.django',
        'HOST': 'database',
        'USER': 'user',
        'PASSWORD': 'password',
        'OPTIONS': {
          'autocommit': True,
        },
    }
}
