# Generated by Django 2.2.6 on 2019-10-01 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(null=True)),
                ('mador', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forums', to='custom_auth.Mador')),
                ('users', models.ManyToManyField(related_name='forums', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
