# Generated by Django 2.2.6 on 2019-10-16 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, default='', null=True)),
                ('budget', models.IntegerField(default=0)),
                ('mador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forums', to='custom_auth.Mador')),
                ('users', models.ManyToManyField(related_name='forums', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'get_latest_by': '-date',
            },
        ),
    ]
